services:
  frontend:
    image: node:16
    command: npm run dev
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    environment:
      HOST: 0.0.0.0
      CMS_URL: http://localhost:3001/
